In [1]:
# import dependencies
import pandas as pd
import numpy as np

In [3]:
# read in csv file for data
all_data = pd.read_csv("Resources/all_data.csv")

# read in csv for lat/lng
coordinates = pd.read_csv("Resources/coords.csv", encoding="Latin-1")

Index(['Year', 'Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual'],
      dtype='object')

,Year,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,2015,Afghanistan,Southern Asia,153,3.575,0.319820,0.302850,0.303350,0.23414,0.097190,0.365100,1.952100
1,2016,Afghanistan,Southern Asia,154,3.360,0.382270,0.110370,0.173440,0.16430,0.071120,0.312680,2.145580
2,2017,Afghanistan,Southern Asia,141,3.794,0.401477,0.581543,0.180747,0.10618,0.061158,0.311871,2.150801
3,2018,Afghanistan,Southern Asia,145,3.632,0.332000,0.537000,0.255000,0.08500,0.036000,0.191000,NaN
4,2019,Afghanistan,Southern Asia,154,3.203,0.350000,0.517000,0.361000,0.00000,0.025000,0.158000,NaN

In [12]:
# groupby object for country and region
country_group_df = all_data.groupby(['Country','Region']).mean()
country_group_df = country_group_df.reset_index()
country_group_df.head()
# merge coordinates to dataframe
merged_df = country_group_df.merge(coordinates, how="left", left_on="Country", right_on="name")

# drop year column
merged_df = merged_df.drop(columns=["Year","name","country"])
merged_df.head()

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,latitude,longitude
0,Afghanistan,Southern Asia,149.4,3.51280,0.357113,0.409753,0.254707,0.117924,0.058094,0.267730,2.082827,33.939110,67.709953
1,Albania,Central and Eastern Europe,106.4,4.71260,0.938633,0.754931,0.787696,0.371898,0.043201,0.167887,1.772514,41.153332,20.168331
2,Algeria,Middle East and Northern Africa,66.2,5.66760,1.012963,1.074205,0.665057,0.178437,0.146099,0.069219,2.802911,28.033886,1.659626
3,Angola,Sub-Saharan Africa,140.0,3.87225,0.798380,0.938368,0.133902,0.027433,0.071570,0.105269,1.886154,-11.202692,17.873887
4,Argentina,Latin America and Caribbean,31.2,6.45940,1.111035,1.330960,0.760895,0.481620,0.064308,0.092371,2.859952,-38.416097,-63.616672

In [17]:
merged_df["Country"].count()

167

In [ ]:
# find countries that have some missing data (didn't participate every year, etc)

In [ ]:
# group by region

# group by country

# group by year

In [ ]:
# create summary table with statistics

In [ ]:
# create heatmap from google maps API (weight = happiness score)

In [ ]:
# find top 5 / bottom 5 for each year

In [ ]:
# find countries with biggest change in rankings/ratings

In [ ]:
# aggregate average for each country

# scatterplot matrix (as heatmap) to see correlations for each variable

# chart GDP vs Life expectancy (or other variables for a country)