In [1]:
# import dependencies
import pandas as pd
import numpy as np
import gmaps
import requests
from config import key_dict
gkey=key_dict["maps"]

In [2]:
# read in csv file for data
all_data = pd.read_csv("Resources/all_data.csv")

# read in csv for lat/lng
coordinates = pd.read_csv("Resources/coords.csv", encoding="Latin-1")
all_data.columns

Index(['Year', 'Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual'],
      dtype='object')

In [3]:
# merge all_data and coordinates
merged_group_df=all_data.merge(coordinates, how="left", left_on="Country", right_on="name")
merged_group_df

,Year,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,country,latitude,longitude,name
0,2015,Afghanistan,Southern Asia,153,3.575,0.319820,0.302850,0.303350,0.234140,0.097190,0.365100,1.952100,AF,33.939110,67.709953,Afghanistan
1,2016,Afghanistan,Southern Asia,154,3.360,0.382270,0.110370,0.173440,0.164300,0.071120,0.312680,2.145580,AF,33.939110,67.709953,Afghanistan
2,2017,Afghanistan,Southern Asia,141,3.794,0.401477,0.581543,0.180747,0.106180,0.061158,0.311871,2.150801,AF,33.939110,67.709953,Afghanistan
3,2018,Afghanistan,Southern Asia,145,3.632,0.332000,0.537000,0.255000,0.085000,0.036000,0.191000,NaN,AF,33.939110,67.709953,Afghanistan
4,2019,Afghanistan,Southern Asia,154,3.203,0.350000,0.517000,0.361000,0.000000,0.025000,0.158000,NaN,AF,33.939110,67.709953,Afghanistan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,2015,Zimbabwe,Sub-Saharan Africa,115,4.610,0.271000,1.032760,0.334750,0.258610,0.080790,0.189870,2.441910,ZW,-19.015438,29.154857,Zimbabwe
778,2016,Zimbabwe,Sub-Saharan Africa,131,4.193,0.350410,0.714780,0.159500,0.254290,0.085820,0.185030,2.442700,ZW,-19.015438,29.154857,Zimbabwe
779,2017,Zimbabwe,Sub-Saharan Africa,138,3.875,0.375847,1.083096,0.196764,0.336384,0.095375,0.189143,1.597970,ZW,-19.015438,29.154857,Zimbabwe
780,2018,Zimbabwe,Sub-Saharan Africa,144,3.692,0.357000,1.094000,0.248000,0.406000,0.099000,0.132000,NaN,ZW,-19.015438,29.154857,Zimbabwe
781,2019,Zimbabwe,Sub-Saharan Africa,146,3.663,0.366000,1.114000,0.433000,0.361000,0.089000,0.151000,NaN,ZW,-19.015438,29.154857,Zimbabwe

In [4]:
# check if there is null values
merged_group_df.isnull().sum()

Year                               0
Country                            0
Region                             0
Happiness Rank                     0
Happiness Score                    0
Economy (GDP per Capita)           0
Family                             0
Health (Life Expectancy)           0
Freedom                            0
Trust (Government Corruption)      1
Generosity                         0
Dystopia Residual                312
country                           40
latitude                          36
longitude                         36
name                              36
dtype: int64

In [5]:
# find out the countries that has no coordinates
index=merged_group_df[merged_group_df["latitude"].isnull()].index.tolist()
merged_group_df.loc[index,"Country"]

154    Congo (Brazzaville)
155    Congo (Brazzaville)
156    Congo (Brazzaville)
157    Congo (Brazzaville)
158    Congo (Brazzaville)
159       Congo (Kinshasa)
160       Congo (Kinshasa)
161       Congo (Kinshasa)
162       Congo (Kinshasa)
163       Congo (Kinshasa)
326            Ivory Coast
327            Ivory Coast
328            Ivory Coast
329            Ivory Coast
330            Ivory Coast
409              Macedonia
410              Macedonia
411              Macedonia
412              Macedonia
477                Myanmar
478                Myanmar
479                Myanmar
480                Myanmar
481                Myanmar
516           North Cyprus
517           North Cyprus
518           North Cyprus
519        North Macedonia
520           North Cyprus
521           North Cyprus
628      Somaliland region
629      Somaliland Region
640            South Sudan
641            South Sudan
642            South Sudan
643            South Sudan
Name: Country, dtype: object

### When merge how="left", we got 8 counties without coordinates, we can either find out the coordinates for these countries or we can drop those countries by dropna or merge by inner

In [6]:
# merge inner
merged_group_df=all_data.merge(coordinates, how="inner", left_on="Country", right_on="name")
merged_group_df

,Year,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,country,latitude,longitude,name
0,2015,Afghanistan,Southern Asia,153,3.575,0.319820,0.302850,0.303350,0.234140,0.097190,0.365100,1.952100,AF,33.939110,67.709953,Afghanistan
1,2016,Afghanistan,Southern Asia,154,3.360,0.382270,0.110370,0.173440,0.164300,0.071120,0.312680,2.145580,AF,33.939110,67.709953,Afghanistan
2,2017,Afghanistan,Southern Asia,141,3.794,0.401477,0.581543,0.180747,0.106180,0.061158,0.311871,2.150801,AF,33.939110,67.709953,Afghanistan
3,2018,Afghanistan,Southern Asia,145,3.632,0.332000,0.537000,0.255000,0.085000,0.036000,0.191000,NaN,AF,33.939110,67.709953,Afghanistan
4,2019,Afghanistan,Southern Asia,154,3.203,0.350000,0.517000,0.361000,0.000000,0.025000,0.158000,NaN,AF,33.939110,67.709953,Afghanistan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,2015,Zimbabwe,Sub-Saharan Africa,115,4.610,0.271000,1.032760,0.334750,0.258610,0.080790,0.189870,2.441910,ZW,-19.015438,29.154857,Zimbabwe
742,2016,Zimbabwe,Sub-Saharan Africa,131,4.193,0.350410,0.714780,0.159500,0.254290,0.085820,0.185030,2.442700,ZW,-19.015438,29.154857,Zimbabwe
743,2017,Zimbabwe,Sub-Saharan Africa,138,3.875,0.375847,1.083096,0.196764,0.336384,0.095375,0.189143,1.597970,ZW,-19.015438,29.154857,Zimbabwe
744,2018,Zimbabwe,Sub-Saharan Africa,144,3.692,0.357000,1.094000,0.248000,0.406000,0.099000,0.132000,NaN,ZW,-19.015438,29.154857,Zimbabwe
745,2019,Zimbabwe,Sub-Saharan Africa,146,3.663,0.366000,1.114000,0.433000,0.361000,0.089000,0.151000,NaN,ZW,-19.015438,29.154857,Zimbabwe

In [7]:
merged_group_df.isnull().sum()

Year                               0
Country                            0
Region                             0
Happiness Rank                     0
Happiness Score                    0
Economy (GDP per Capita)           0
Family                             0
Health (Life Expectancy)           0
Freedom                            0
Trust (Government Corruption)      1
Generosity                         0
Dystopia Residual                298
country                            4
latitude                           0
longitude                          0
name                               0
dtype: int64

In [8]:
# gather columns we need 
clean_data=merged_group_df[['Year', 'Region','Country','latitude','longitude', 'Happiness Rank', 'Happiness Score',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity']]
clean_data

,Year,Region,Country,latitude,longitude,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity
0,2015,Southern Asia,Afghanistan,33.939110,67.709953,153,3.575,0.319820,0.302850,0.303350,0.234140,0.097190,0.365100
1,2016,Southern Asia,Afghanistan,33.939110,67.709953,154,3.360,0.382270,0.110370,0.173440,0.164300,0.071120,0.312680
2,2017,Southern Asia,Afghanistan,33.939110,67.709953,141,3.794,0.401477,0.581543,0.180747,0.106180,0.061158,0.311871
3,2018,Southern Asia,Afghanistan,33.939110,67.709953,145,3.632,0.332000,0.537000,0.255000,0.085000,0.036000,0.191000
4,2019,Southern Asia,Afghanistan,33.939110,67.709953,154,3.203,0.350000,0.517000,0.361000,0.000000,0.025000,0.158000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,2015,Sub-Saharan Africa,Zimbabwe,-19.015438,29.154857,115,4.610,0.271000,1.032760,0.334750,0.258610,0.080790,0.189870
742,2016,Sub-Saharan Africa,Zimbabwe,-19.015438,29.154857,131,4.193,0.350410,0.714780,0.159500,0.254290,0.085820,0.185030
743,2017,Sub-Saharan Africa,Zimbabwe,-19.015438,29.154857,138,3.875,0.375847,1.083096,0.196764,0.336384,0.095375,0.189143
744,2018,Sub-Saharan Africa,Zimbabwe,-19.015438,29.154857,144,3.692,0.357000,1.094000,0.248000,0.406000,0.099000,0.132000
745,2019,Sub-Saharan Africa,Zimbabwe,-19.015438,29.154857,146,3.663,0.366000,1.114000,0.433000,0.361000,0.089000,0.151000

In [9]:
# group by region and country
group_df = clean_data.groupby(['Region','Country']).mean()

In [10]:
# heatmap for all the countries 
gmaps.configure(api_key=gkey)
fig=gmaps.figure()
locations=group_df[["latitude","longitude"]].astype(float)
happiness=group_df["Happiness Score"].astype(float)
heat_layer=gmaps.heatmap_layer(locations,weights=happiness,
                               dissipating=False, max_intensity=5, 
                               point_radius=3)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# find the top ten countries
top_ten=group_df.sort_values(by=["Happiness Score"],ascending=False).head(10)
top_ten=top_ten.reset_index()
top_ten

,Region,Country,Year,latitude,longitude,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity
0,Western Europe,Denmark,2017.0,56.263920,9.501785,2.2,7.5460,1.396729,1.447688,0.865249,0.625959,0.429374,0.318876
1,Western Europe,Norway,2017.0,60.472024,8.468946,2.8,7.5410,1.519381,1.431075,0.873333,0.638049,0.343951,0.328990
2,Western Europe,Finland,2017.0,61.924110,25.748151,3.6,7.5378,1.356960,1.434429,0.873836,0.621536,0.398474,0.217783
3,Western Europe,Switzerland,2017.0,46.818188,8.227512,3.6,7.5114,1.472164,1.417332,0.928318,0.620642,0.379763,0.277432
4,Western Europe,Iceland,2017.0,64.963051,-19.020835,3.2,7.5110,1.386523,1.492813,0.917744,0.618035,0.140145,0.419124
5,Western Europe,Netherlands,2017.0,52.132633,5.291266,6.2,7.4046,1.411013,1.349646,0.878569,0.589651,0.298614,0.415150
6,North America,Canada,2017.0,56.130366,-106.346771,6.8,7.3506,1.388129,1.387412,0.900558,0.610954,0.305846,0.389598
7,Western Europe,Sweden,2017.0,60.128161,18.643501,8.6,7.3192,1.403981,1.368574,0.898991,0.617581,0.397502,0.336512
8,Australia and New Zealand,New Zealand,2017.0,-40.900557,174.885971,8.2,7.3130,1.317509,1.439729,0.891618,0.617782,0.400015,0.432805
9,Australia and New Zealand,Australia,2017.0,-25.274398,133.775136,10.0,7.2762,1.394885,1.409006,0.914529,0.605043,0.314573,0.416078

In [12]:
# mark top ten countries
coordinates=top_ten[["latitude","longitude"]].astype(float)
top_symbol=gmaps.symbol_layer(coordinates,
                           info_box_content=top_ten["Country"],
                          stroke_color="green")
fig.add_layer(top_symbol)
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
botomn_ten=group_df.sort_values(by=["Happiness Score"],ascending=False).tail(10)
botomn_ten=botomn_ten.reset_index()
botomn_ten

,Region,Country,Year,latitude,longitude,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity
0,Sub-Saharan Africa,Botswana,2017.00,-22.328474,24.684866,140.20,3.83000,1.053581,1.107411,0.338407,0.490607,0.104603,0.079042
1,Sub-Saharan Africa,Madagascar,2017.00,-18.766947,46.869107,145.00,3.74540,0.265918,0.773236,0.434105,0.177375,0.062706,0.193293
2,Middle East and Northern Africa,Yemen,2017.00,15.552727,48.516388,146.40,3.62580,0.489313,0.865448,0.365440,0.244175,0.067045,0.096929
3,Sub-Saharan Africa,Togo,2017.00,8.619543,0.824782,148.20,3.54420,0.265871,0.323567,0.288529,0.363747,0.100969,0.174775
4,Southern Asia,Afghanistan,2017.00,33.939110,67.709953,149.40,3.51280,0.357113,0.409753,0.254707,0.117924,0.058094,0.267730
5,Sub-Saharan Africa,Tanzania,2017.00,-6.369028,34.888822,150.80,3.46600,0.439777,0.939380,0.396732,0.386880,0.083699,0.311749
6,Sub-Saharan Africa,Rwanda,2017.00,-1.940278,29.873888,152.00,3.43860,0.322057,0.788453,0.417543,0.581611,0.473468,0.226311
7,Middle East and Northern Africa,Syria,2017.00,34.802075,38.996815,152.60,3.29220,0.699109,0.355931,0.566281,0.081700,0.159547,0.431285
8,Sub-Saharan Africa,Central African Republic,2017.25,6.611111,20.939444,153.25,3.13425,0.032125,0.000000,0.050191,0.322408,0.053114,0.243057
9,Sub-Saharan Africa,Burundi,2017.00,-3.373056,29.918886,153.80,3.07900,0.062447,0.470817,0.211608,0.101320,0.106992,0.185921

In [20]:
# mark bottom ten countries
coordinates=botomn_ten[["latitude","longitude"]].astype(float)
markers=gmaps.symbol_layer(coordinates,
                           info_box_content=botomn_ten["Country"],
                          stroke_color="blue")
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))

In [15]:
# group by year
year_df = clean_data.groupby('Year')
year_df["Happiness Score"].describe()

      count      mean       std    min      25%     50%     75%    max
Year
2015  151.0  5.411517  1.150473  2.839  4.56800  5.2860  6.2965  7.587
2016  149.0  5.425523  1.146837  2.905  4.50800  5.4400  6.3550  7.526
2017  148.0  5.391899  1.134475  2.693  4.54625  5.3175  6.2120  7.537
2018  149.0  5.413329  1.120203  2.905  4.47100  5.4300  6.1920  7.632
2019  149.0  5.443812  1.110663  3.083  4.55900  5.4300  6.1980  7.769

In [26]:
def data(year):
    return clean_data.loc[(clean_data["Year"].astype(float)==year)
               &(clean_data["Happiness Score"].astype(float)>=7.35)]
data(2015)

,Year,Region,Country,latitude,longitude,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity
122,2015,North America,Canada,56.130366,-106.346771,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811
174,2015,Western Europe,Denmark,56.263920,9.501785,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139
210,2015,Western Europe,Finland,61.924110,25.748151,6,7.406,1.29025,1.31826,0.88911,0.64169,0.41372,0.23351
276,2015,Western Europe,Iceland,64.963051,-19.020835,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630
467,2015,Western Europe,Netherlands,52.132633,5.291266,7,7.378,1.32944,1.28017,0.89284,0.61576,0.31814,0.47610
492,2015,Western Europe,Norway,60.472024,8.468946,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699
626,2015,Western Europe,Sweden,60.128161,18.643501,8,7.364,1.33171,1.28907,0.91087,0.65980,0.43844,0.36262
631,2015,Western Europe,Switzerland,46.818188,8.227512,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678

In [17]:
# find countries that have some missing data (didn't participate every year, etc)

In [ ]:
# group by region

# group by country

# group by year

In [ ]:
# create summary table with statistics

In [ ]:
# create heatmap from google maps API (weight = happiness score)

In [ ]:
# find top 5 / bottom 5 for each year

In [ ]:
# find countries with biggest change in rankings/ratings

In [ ]:
# aggregate average for each country

# scatterplot matrix (as heatmap) to see correlations for each variable

# chart GDP vs Life expectancy (or other variables for a country)

In [ ]:
<<<<<<< REMOTE CELL DELETED >>>>>>>
all_data = pd.read_csv("./Resources/all_data.csv")
#all_data.iloc[0:10, :]
all_data.head(10)

In [ ]:
all_data.groupby("Region").mean()

In [ ]:
all_data.groupby("Country").mean()